- name: Copying the {{Component}} repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo    

- name: Installing {{Component}}}
  ansible.builtin.package:
     name: mongodb-org
     state: present

- name: Configuring the {{Component}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{Component}}
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Downloading & Extracting {{Component}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Injecting the {{Component}} schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{itemt}}.js"
    idempotent: yes
  loop:
    - users
    - catalogue

- name: Configuring Service name
  ansible.builtin.shell: set-hostname {{Component}}-{{ENV}}
