- name: Demo on vars usage
  hosts: all
  vars:                 # Global variable: All the tasks of this play can access this variable
    URL: play.google.com 
  tasks: 
    - name: Printing hi from task1 of play1
      ansible.builtin.debug:
        msg: Value of url is {{URL}}
    
    - name: Demo on using local variable
      ansible.builtin.debug:
        msg: Value of link is {{URL}}
      vars:
        URL: task.google.com

# Variable precedence:
# local variable > global variable




