- name: Demo on vars usage
  hosts: all
  vars:                 # Global variable: All the tasks of this play can access this variable
    URL: play.google.com 
  vars_files:
    - dev.yml
  vars_prompt:
    - name: YourName
      prompt: Enter your name
      private: false          # True/false are booleans where by default tue will be selected, if true the string which we type cannot be seen, if false then it can be seen
  tasks: 
    - name: Printing hi from task1 of play1
      ansible.builtin.debug:
        msg: Value of url is {{URL}}
    
    - name: Demo on using local variable
      ansible.builtin.debug:
        msg: Value of link is {{URL}}
      vars:
        URL: task.google.com
    
#    - name: Printing prompt variable
#     ansible.builtin.debug:
#        msg: Name of the person is {{YourName}}
    - name: This is env specific
      ansible.builtin.debug:
        msg: Type of instance to be used {{INS_TYPE}}

# Variable precedence:
# command line variales > local variable > global variable
# If we try to print a variable without declaring it, it will throw a error





