- name: Demo on errors
  hosts: all
  tasks:
  - name: Check tomcat is running or not
    ansible.builtin.shell: ps -ef | grep java | grep -v grep
    register: OUT
    ignore_errors: yes

  - name: Starting Tomcat
    ansible.builtin.debug: 
      msg: Tomcat is started

# If any of the task fails in playbook, then the sub-sequent task will also fail and playbook will be exited 