- name: Demo on Conditions
  hosts: all
  vars:
    action: true
  tasks:
    - name: Run this only when the distribution is centos
      ansible.builtin.debug:
        msg: Welcome to Centos {{ansible_distribution}}
      when: ansible_distribution == "CentOS"

    - name: Run this only when the distribution is Ubuntu
      ansible.builtin.debug:
        msg: Welcome to Ubuntu {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"
    
    - name: Run this action
      ansible.builtin.debug:
        msg: Action is true
      when: action

# When action is false, the action will be skipped since its not serving the criteria
    - name: Run this task when action variable is declared
      ansible.builtin.debug:
        msg: Action variable is declared
      when: action is defined 