- name: Demo on using tags
  hosts: all

  tasks:
  - name: This is a frontend task
    ansible.builtin.debug:
      msg: Installing frontend
    tags: frontend

  - name: This is a frontend task
    ansible.builtin.debug:
      msg: Starting frontend
    tags: frontend

  - name: This is a backend task
    ansible.builtin.debug:
      msg: Installing backend
    tags: backend

  - name: This is a backend task
    ansible.builtin.debug:
      msg: Starting backend
    tags: backend

  - name: This is a DB task
    ansible.builtin.debug:
      msg: Installing DB
    tags: DB

  - name: This is a DB task
    ansible.builtin.debug:
      msg: Starting DB
    tags: DB

# Tags are basically a keyword given to a task, if we want to execute only the frontend process we use frontend tag or only the backend process then backend tag
# $ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 07-tags.yml -t DB | command used with tags