- name: Demo on previlege escalation
  hosts: all
  become: yes           # previlege escalation: Runs the playbook as rootuser
  tasks:
  - name: Checking user ID
    ansible.builtin.shell: id
    register: OUT

  - name: Printing the user ID
    ansible.builtin.debug: 
      msg: "{{OUT}}"