- name: Demo on loops
  hosts: all
  tasks:
  - name: Demo on using loops 
    ansible.builtin.debug:
      msg: "Value is {{item}}"      # Item is a keyword used to represent te value in the loop
    loop:
      - 100
      - 200
      - 300
      