- name: Demo on installing packages
  hosts: all
  become: yes
  tasks:
  - name: Removing packages
    ansible.builtin.package:
      name: 
        - nginx
        - httpd
        - jq
      state: absent
  