- name: Demo on installing packages
  hosts: all
  become: yes
  tasks:
  - name: Installing packages
    ansible.builtin.package:
      name: 
        - nginx
        - httpd
        - jq
      state: present
  