- name: Demo on installing packages
  hosts: all
  become: yes
  tasks:
  - name: Removing nginx
    ansible.builtin.package:
      name: nginx
      state: absent
  
  - name: Installing httpd
    ansible.builtin.package:
      name: httpd
      state: absent

  - name: Installing jq
    ansible.builtin.package:
      name: jq
      state: absent