- name: Installing ERLang package
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/{{Component}}/erlang/script.rpm.sh | bash

- name: Configuring {{Component}} repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/{{Component}}/{{Component}}-server/script.rpm.sh | bash
  
- name: Installing {{Component}}
  ansible.builtin.package:
     name: rabbitmq-server
     state: present

- name: Starting {{Component}}
  systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Creating {{APPUSER}} user on {{Component}}
  community.rabbitmq.rabbitmq_user:
    user: "{{APPUSER}}"
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .* 
        write_priv: .* 
    state: present
