- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copying the Elastic Repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo 

- name: Installing filebeat
  ansible.builtin.package: 
    name: filebeat
    state: present

- name: Copying the filebeat config
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml  

- name: Starting filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
    daemon_reload: yes

Install the repo
sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

Configure the repo to yum

sudo yum install filebeat

sudo systemctl enable filebeat

sudo systemctl start filebeat