# Configures logstash
- name: Copying the logstash config
  ansible.builtin.template:
    src: logstash.config
    dest: /etc/logstash/conf.d/logstash.conf  

- name: Restarting logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes
    daemon_reload: yes
