- name: Configuring the {{Component}} repo
  ansible.builtin.copy:
    src: "{{Component}}.repo"
    dest: /etc/yum.repos.d/{{Component}}.repo    

- name: Installing {{Component}}}
  ansible.builtin.package:
     name: mysql-community-server
     state: present

- name: Starting {{Component}}
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Fetches the log file from the remote node
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: pwd_log

- name: Extracting the root password
  ansible.builtin.set_fact: 
    DEFAULT_PASSWORD: "{{ pwd_log['content'] | b64decode | regex_findall('.*temporary password.*') }}"

- name: Printing
  ansible.builtin.debug: 
    msg: value is {{DEFAULT_PASSWORD}}
    
- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name

