- name: Configuring Nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Nodejs
  ansible.builtin.package:
     name: Nodejs
     state: present

- name: Creating {{APPUSER}}
  ansible.builtin.user:
    name: {{APPUSER}}
    comment: Roboshop app user

- name: Downloading & Extracting the file
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes  

- name: Performing {{Component}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{Component}}
    state: absent
  ignore_errors: yes

- name: Copying the file to {{APPUSER}} home directory
  ansible.builtin.copy:
    src: /tmp/{{Component}}-main/
    dest: /home/{{APPUSER}}/{{Component}}
    remote_src: yes 