- name: Copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{Component}}.service
    
- name: Starting {{Component}}
  systemd:
    name: "{{Component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes


