- name: Performing {{COMPONENT}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes

- name: Create a APP Directory
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: directory
  become_user: "{{APPUSER}}"

- name: Downloading & Extracting the file
  ansible.builtin.unarchive:
    src: http://172.31.37.89:8081/repository/${{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes  


