- name: Installing Maven on {{COMPONENT}}-{{ENV}} Server
  ansible.builtin.package:
     name: maven
     state: present

- name: Creating APPUSER
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Downloading and Extracting the file
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extract

- name: Generating artifacts with npm Install
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring the {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name
