- name: Configuring Nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Nodejs
  ansible.builtin.package:
     name: nodejs
     state: present

- name: Creating APPUSER
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

# - name: Downloading .pem file
#   ansible.builtin.get_url:
#     url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
#     dest: /home/{{APPUSER}}/global-bundle.pem
#   become_user: "{{APPUSER}}"
  
# Downloads the code directly from github
# - name: Downloading and Extracting the file
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_extract

- name: Downloading and Extracting the {{COMPONENT}} from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

# Only use this when you want to download install it from github, with CI in place, we use nexus
# - name: Generating artifacts with npm Install
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring the {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name
