- name: Installing Python
  ansible.builtin.package:
     name:
      - python36
      - python3-devel
      - gcc
     state: present

- name: Creating APPUSER
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Downloading and Extracting the file
  ansible.builtin.include_role:
    name: common
    tasks_from: download_extract

- name: Updating the UID of {{Component}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{Component}}/{{Component}}.ini
    regexp: '^uid'
    line: uid = {{USERINFO.group}}

- name: Updating the GID of {{Component}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{Component}}/{{Component}}.ini
    regexp: '^gid'
    line: gid = {{USERINFO.group}}

- name: Configuring the {{Component}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name