- name: Installing Python
  ansible.builtin.package:
     name:
      - python36
      - python3-devel
      - gcc
     state: present

- name: Creating APPUSER
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

# - name: Downloading and Extracting the file
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_extract

- name: Downloading and Extracting the {{COMPONENT}} from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

- name: Updating the UID of {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{USERINFO.group}}

- name: Updating the GID of {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{USERINFO.group}}

- name: Installing APP Dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.6
    
- name: Configuring the {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Installing Rsyslog
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Installing Filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Installing Node Exporter
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name